### ISSUE TITLE
Correct prompt for Llama2-chat

### ISSUE THREAD

**Issue by ChenxinAn-fdu** [THUDM/LongBench#2]
Hi! Firstly, I am very glad for the great work on the bilingual dataset!  However, based on my experiments on LEval, LLama2-chat has a very strong ability on long document tasks.  But the results seem divergent on LongBench. And I think a potential reason is that we use different prompt formats. 
Here is my prompt: B_INST + B_SYS + system_prompt + E_SYS + context + instruction + E_INST.  
The context is truncated from the right~

**Comment by bys0318** [comment]
Hi! Here is the prompt we use for Llama2-chat: B_INST + input_text + E_INST, where input_text is formatted according to `config/dataset2prompt.json`. We use middle truncation to avoid vital information loss. In order to best mimic the real scenario, we skip using system prompt (B_SYS and E_SYS) as users often find it difficult to distinguish system prompt from instructions. The same applies to all other models we evaluate.

**Comment by ChenxinAn-fdu** [comment]
Thank you for your response!  Using the same setting for all models is reasonable.  
Prompt engineering is sooo interesting.

**Comment by bys0318** [comment]
Agreed~Nice work on LEval BTW :)
