### ISSUE TITLE
Max length not guarenteed

### ISSUE THREAD

**Issue by fuvty** [THUDM/LongBench#21]
In `pred.py`, max length is applied before `build_chat`. Yet after `build_chat`, some sentences may exceed max_length, which may cause performance breakdown if the model's max token length is equal to `max_length`.

**Comment by bys0318** [comment]
You are right. That's why we set the maximum length in [model2maxlen.json](https://github.com/THUDM/LongBench/blob/main/config/model2maxlen.json) a bit shorter than the model's max token length, guaranteeing that even after adding the `build_chat` and the model's generation output, the length won't exceed the model's max token length.

**Comment by fuvty** [comment]
Thank you for your timely response! I'll use the same practice to test the model as well. 
Personally, I would suggest adding "a big shorter" length as an argument to make sure that all models are tested in the same manner.
