### ISSUE TITLE
directly cutting from the middle seems unfair

### ISSUE THREAD

**Issue by Arist12** [THUDM/LongBench#25]
It isn't a fair comparison to me if the prompt is cut from the middle.

If the answer resides in the middle of the prompt, doing this will result in an absolute error. If the answer isn't cut away, the task is literally made easier by removing answer-unrelated messages. So LongBench actually can't provide a fair comparison of all models long context ability (those models with shorter context length are evaluated on easier tasks)

**Comment by bys0318** [comment]
Thanks for your attention! For models with a length limit, truncation is necessary. We use middle truncation during evaluations because the information at the beginning and end of general text is usually most important. In practical applications, middle truncation is often the truncation method that best persists performance. Admittedly, the input of these models is shorter after truncation, making the task easier, but their performance are also compromised due to the truncation of potential key information. 
We also compare the performance of the models at different text lengths and truncation lengths in our [paper](https://arxiv.org/abs/2308.14508). We hope these results could address your concerns about the fairness of the evaluation.

**Comment by Arist12** [comment]
Thank you for your response.
I would like to express my concern regarding the inclusion of models with different context lengths in the same table. It appears to be inappropriate since these models are not even playing identical tasks. 
Moreover, I noticed that there is no statistical data available regarding the percentage of answers that are being truncated for a given task. This information is crucial, especially given the lengths of tasks (which can easily reach tens of thousands) in LongBench. It is highly plausible that the sentence containing the final answer may be cut off from the middle, especially for llama2-chat-4k, and renders the evaluation meaningless (think about evaluating on a task where half of the test sample is not even solvable).

**Comment by bys0318** [comment]
Thanks for pointing them out! We design and construct LongBench with behavioral mindset, trying to use the closest scenarios to real applications to evaluate the real performance of the model under long text. As a result, the performance of the models on our benchmark can also most realistically reflect its reply quality in real scenarios.
In practice, truncation is a necessary means for inputs whose length exceeds the maximum length accepted by the model, and thus we implement truncation during evaluation experiments to best mimic the real-world scenarios.

**Comment by bys0318** [comment]
Related issue: #12
